version: '3.7'

services:
  app:
    build: .
    container_name: k1core_app
    ports:
      - ${FASTAPI_APP_PORT}:${FASTAPI_APP_PORT}
      - ${DJANGO_APP_PORT}:${DJANGO_APP_PORT}
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    command: ./scripts/runlocalserver.sh
    volumes:
      - .:/k1core

  db:
    image: postgres:14
    container_name: k1core_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres_db:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: k1core_redis

  celery-worker:
    build: .
    container_name: k1core_celery_worker
    depends_on:
      - app
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    command: celery -A config.celery worker --loglevel=error

  celery-beat:
    build: .
    container_name: k1core_celery_beat
    depends_on:
      - app
      - redis
      - db
      - celery-worker
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    command: celery -A config.celery beat --loglevel=error

  flower:
    image: mher/flower
    container_name: k1core_flower
    ports:
      - ${FLOWER_PORT}:${FLOWER_PORT}
    depends_on:
      - redis
      - db
      - celery-worker
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - FLOWER_PORT=${FLOWER_PORT}

volumes:
  postgres_db:
